kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: x-azurefile
provisioner: file.csi.azure.com  #replace with "kubernetes.io/azure-file" if aks version is less than 1.21
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - mfsymlinks
 - cache=strict
 - actimeo=30
parameters:
   skuName: Standard_LRS
