apiVersion: v1
kind: Pod
metadata:
    name: my-container
spec:
  volumes:
  - name: logs-volume
    emptyDir: {}
  containers:
  - image: nginx:1.23.4
    name: my-container
    volumeMounts:
    - mountPath: /var/logs
      name: logs-volume
